apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncouse-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncouse-app
  template:
    metadata:
      labels:
        app: syncouse-app
    spec:
      containers:
        - name: app
          image: yash3123/syncouse:v1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db:3306/HMS?characterEncoding=utf8
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
